### PR TITLE
Minor additions

### LINKED ISSUE #60: Add method of inflating menu for BottomNavigationView to dsl.

### PR DESCRIPTION
**Pull request by sgrekov**
- inflate menu for  BottomViewNavigation, fixes https://github.com/inkremental/inkremental/issues/60
- text color with compat
- drawable with compat
- content insets for toolbar
- dsl for ripple effects

### CODE REVIEW

**Comment by r4zzz4k** [comment]
Awesome additions. The only thing bothering me a bit is compat scopes. I (probably) understand reasoning, bit I'm not sure this helps API discoverability. Maybe these extensions should belong usual autogenerated scopes? `...Compat` suffix on methods could be enough.

**Comment by sgrekov** [comment]
Yeah, this was my initial approach. But then the question arise, at what moment or how should we add CustomSupportV4Setter to global attribute setters?

**Comment by r4zzz4k** [comment]
`manualSetterName` should be enough, it makes the setter to be added to each and every scope of the library.

**Comment by r4zzz4k** [comment]
Okay, I see the problem after clarifications in chat. Let's leave it as is.

**Review by r4zzz4k — APPROVED** [review]

**Review by Mishkun — APPROVED** [review]

**Pull request merged**
