### PR TITLE
GitHub actions

### LINKED ISSUE #29: Decide on CI
Right now we have both Circle CI (#1) and Travis set up. Travis config is up to date, CircleCI needs attention. We should decide which one we would use, configure it if needed and disable the other one.

### PR DESCRIPTION
**Pull request by r4zzz4k**
* Updated version to 0.9
* Replaced sdk-15 with sdk-17 as GitHub Action's default images don't have SDKs lower than 17 and there are no reasons to support it anymore anyway
* Added GitHub Actions to build and run tests on pushes to non-master and to publish on pushes to master
* Disabled overriding when publishing to Bintray

Closes #29

### CODE REVIEW

**Comment by r4zzz4k** [comment]
Right now Actions run publishing on every push to master. Is that okay for us?
It's logical to have fresh artifacts after PR merges. The main question is version management. Leaving it for PR author to decide doesn't sound like a good idea. I'm open to suggestions.

**Comment by r4zzz4k** [comment]
Okay, so it seems that Bintray provides repo for snapshots when enabling sync to JCenter after manual approve. Let's maybe keep it as-is then? Publishing job should now fail if version is kept the same, so this should be safe, and we can always publish manually if needed.

**Comment by r4zzz4k** [comment]
Made publishing step optional so that it doesn't fail run if version is not updated.

**Review by sgrekov — APPROVED** [review]

**Comment by sgrekov** [comment]
So, the current state is that it publishing snapshot on every successful build after merge to master?

**Comment by r4zzz4k** [comment]
Nope, after latest changes it should fail publishing of the version already present in the repo, while the job still counts as successful. So no fresh stuff without changing version, but no silently replaced versions.

**Review by Mishkun — APPROVED** [review]
Seems good

**Comment by r4zzz4k** [comment]
Fixed small issue with min sdk, fixed BinTray publishing.

**Pull request merged**
