### PR TITLE
More dsl with size types

### PR DESCRIPTION
**Pull request by sgrekov**
This PR changes parameters of some of the dsl's to call with with type size qualifiers (Size class). It add more consistency to API overall, fixing some of the Android's broken Java API.
It also fixes bug with casting nullable values of attributes in setters  to non nullable which leads to crashes.
P.S. If you want to skip looking at changes in generated classes, look into 'add more dsls with typed dimension values' commit

### CODE REVIEW

**Comment by r4zzz4k** [comment]
This looks reasonable.

There's one thing that's bothering me though. Right now all custom attribeutes added via extensions don't provide same level of type-safety as autogenerated ones, as they are not covered by `@DslMarker`. In addition to that, this change seems quite repetitive for me, and there is a pattern to it.

So, the idea for consideration: maybe we should add a concept of attribute transformers of some kind, which can be attached to an attribute via quikrs, and which would have an ability to transform codegen for both scopes and setters? I'm not sure if there are any usages right now apart from adapting ints and floats to our sizes, but even this one case can be useful not only for us, but for our consumers with their custom views. And tutorial would mention something like "In quirks section, mark the attribute with this transformer" instead of "In quirks, remove the attribute, then add custom setter, add attribute there, and don't forget to add scope extension".

I'm not 100% sure this does worth it's time investment, but I'd like to have that before 1.0 in case we decide it does.

**Comment by sgrekov** [comment]
Yep, adding some kind of auto transformers will be a good addition. One thing to keep in mind that underlying APIs can be quite different if we will look for example how padding and textsize are set. 
But for APIs similar to the ones that are covered in this PR it won't be too hard to implement such transformer. 
But are you really sure to implement it before 1.0? For me it is mostly nice to have, and can be added afterwards.

**Comment by r4zzz4k** [comment]
This breaks backward compatibility by changing extension functions to members. Though we don't follow semver, it's still not a great thing to do that often.

Although we can declare that 1.x don't make any guarantees on backward compatibility in minor releases and keep it for future. That may be an option to both sign that the library can be used in apps and leave us enough space for doing such moves.

**Review by r4zzz4k — APPROVED** [review]
Okay, leaving that for future via #45 sounds reasonable. I don't have anything other than that, LGTM!

**Review by Mishkun — APPROVED** [review]

**Pull request merged**
